name: Continuous Integration
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

env:
  cache-version: v1

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cache node modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.cache/Cypress
            ~/.npm
            **/node_modules
          key: ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ env.cache-version }}-${{ runner.os }}-build-
            ${{ env.cache-version }}-${{ runner.os }}-

      - name: Cache Cypress
        id: cypress_cache_id
        uses: actions/cache@v3
        env:
          cache-name: cache-cypress
        with:
          path: |
            ~/.cache/Cypress
          key: ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.cache/Cypress/**/Cypress/Cypress') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ env.cache-version }}-${{ runner.os }}-build-
            ${{ env.cache-version }}-${{ runner.os }}-

      - name: Install Dependencies
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' && steps.cypress_cache_id.outputs.cache-hit != 'true' }}
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Cypress 🧪🧪🧪
        run: npm run cypress:ci

      - name: Run Build
        run: npm run build
        env:
          CI: false
